pubAuthor: ORY GmbH
pubAuthorEmail: opensource@ory.sh
pubHomepage: https://www.ory.sh
pubName: ${DART_PUB_NAME}
pubDescription: ${PACKAGE_DESCRIPTION}
pubRepository: ${DART_PUB_REPOSITORY}
pubVersion: $RAW_VERSION

disallowAdditionalPropertiesIfNotPresent: false
