licenseId: Apache-2.0
packageName: "Ory.$PROJECT_UCF.Client"
packageVersion: $RAW_VERSION
packageAuthors: ORY
packageCompany: ORY GmbH
netCoreProjectFile: true
infoUrl: https://www.ory.sh
targetFramework: net5.0
disallowAdditionalPropertiesIfNotPresent: false