groupId: ${JAVA_GROUP_ID}
invokerPackage: ${JAVA_GROUP_ID}
apiPackage: ${JAVA_GROUP_ID}.api
modelPackage: ${JAVA_GROUP_ID}.model

artifactId: ${JAVA_ARTIFACT_ID}
artifactVersion: $VERSION
library: okhttp-gson
dateLibrary: java8
developerName: Ory
developerOrganization: www.ory.sh
developerOrganizationUrl: https://www.ory.sh
developerEmail: office+oss@ory.sh
licenseName: Apache License, Version 2.0
licenseUrl: https://www.apache.org/licenses/LICENSE-2.0

disallowAdditionalPropertiesIfNotPresent: false
