projectName: ${RUBY_PROJECT_NAME}
gemName: ${RUBY_PROJECT_NAME}

gemVersion: $VERSION
library: typhoeus
gemAuthorEmail: opensource@ory.sh
gemAuthor: ORY GmbH
gemHomepage: https://www.ory.sh
gemLicense: Apache-2.0
moduleName: ${RUBY_MODULE_NAME}
