npmName: "${NPM_NAME}-fetch"
npmVersion: $VERSION
# typescriptThreePlus: true
supportsES6: true
ensureUniqueParams: true
modelPropertyNaming: original
disallowAdditionalPropertiesIfNotPresent: false
withInterfaces: false
useSingleRequestParameter: true
enumUnknownDefaultCase: true
