name: ory_kratos_client
version: 1.3.6
description: OpenAPI API client for Ory Kratos, Ory&#39;s central identity management solution with hardened authentication, MFA, FIDO2, TOTP, WebAuthn, SSO, profile management, and more.
homepage: https://www.ory.sh
repository: https://github.com/ory/sdk/tree/master/clients/kratos/dart

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  dio: '^5.2.0'
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'

dev_dependencies:
  built_value_generator: '>=8.4.0 <9.0.0'
  build_runner: any
  test: ^1.16.0
