name: CI
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: oryd/sdk:v0.0.50
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        language:
          [
            "elixir",
            "typescript",
            "rust",
            "golang",
            "java",
            "php",
            "python",
            "ruby",
            "dotnet",
            "dart",
          ]
    steps:
      - run: cp -r /root/. $HOME # Workaround, because $HOME is set to /github/home inside the action run
      - run: ls -la .
      - uses: actions/checkout@v3
      - name: "client"
        run: ./scripts/generate-and-test.sh ${{ matrix.language }} latest client
      - name: "keto"
        run: ./scripts/generate-and-test.sh ${{ matrix.language }} latest keto
      - name: "kratos"
        run: ./scripts/generate-and-test.sh ${{ matrix.language }} latest kratos
      - name: "hydra"
        run: ./scripts/generate-and-test.sh ${{ matrix.language }} latest hydra
      - name: "oathkeeper"
        run: ./scripts/generate-and-test.sh ${{ matrix.language }} latest oathkeeper
